config/routes.rb
Rails.application.routes.draw do

  resources :line_items, only: [:destroy, :create]
  resources :carts
  resources :products

  devise_for :users

  resources :profiles, only: :show

  root 'products#index'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :line_items

  def subtotal
    line_items.to_a.sum {|item| item.total_price}
  end

  def  add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity +=1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/condition.rb
class Condition < ActiveRecord::Base
  has_many :products
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

def total_price
  product.price * quantity
end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :condition
  belongs_to :user
  has_many :line_items

  has_attached_file :pic, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :pic, :content_type => /\Aimage\/.*\Z/

  geocoded_by :address
  after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  geocoded_by :zip_code
  after_validation :geocode

  has_many :products
  has_many :carts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :username, :bio, :latitude, :longitude, :avatar, :birthday, :zip_code) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :name, :username, :bio, :latitude, :longitude, :avatar, :birthday, :zip_code) }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.find(params[:id])
    unless current_user.id == @cart.user_id
      flash[:notice] = "You don't have access to that order!"
      redirect_to root_path
    end

  end

  def new
    @cart = Cart.new
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if @cart.save
        format.html {redirect_to @cart, notice: "Cart was successfully created"}
      else
        format.html {render :new}
      end
    end
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy if @cart.id ==session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html {redirect_to products_path, notice: "Your Cart was removed."}
    end
  end

  def update
    @cart = Cart.find(params[:id])
    respond_to do |format|
      if @cart.update(cart_params)
        format.html {redirect_to @cart, notice: "Cart was successfully created"}
      else
        format.html {render :edit}
      end
    end
  end

  private
  def cart_params
    params.require(:cart).permit(:user_id)
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  private
    def set_cart
      @cart = Cart.find(session[:cart_id])
      rescue ActiveRecord::RecordNotFound
      @cart = Cart.create(user_id: current_user.id)
      session[:cart_id] = @cart.id
    end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
include CurrentCart
before_action :set_cart, only: [:create]


def create
  product = Product.find(params[:product_id])
  @line_item = @cart.add_product(product.id)
  respond_to do |format|
    if @line_item.save
      format.html {redirect_to cart_path(@line_item.cart_id), notice: "You added #{product.name} to your cart"}
    else
      format.html {redirect_to root_path}
    end
  end
end

def destroy
  @line_items = LineItem.find(params[:id])
  @line_items.destroy
  redirect_to cart_path(line_item.cart_id)
end

private
  def line_items_params
    params.require(:line_items).permit(:product_id, :cart_id, :quantity)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
      if @product.save
        redirect_to @product
      else
        render :new
      end
  end

  def index
    @product = Product.near([current_user.latitude, current_user.longitude], 20)
  end

  def edit
  end

  private
  def product_params
    params.require(:product).permit(:name, :price, :description, :quantity, :latitude, :longitude, :address, :condition_id, :category_id, :user_id, :pic)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :username, :birthday, :bio, :latitude, :longitude, :user_id, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/carts/show.html.erb
<table class= "table table-striped">
<thead>
  <tr>
    <th>
      Product
    </th>
    <th>
      Quantity
    </th>
    <th>
      Unit Price
    </th>
    <th>
      Total Price
    </th>
  </tr>
</thead>
<tbody>
  <% @cart.line_items.each do |item| %>
<tr>
  <td>
    <%= item.product.name %>
  </td>
  <td>
  <%= item.quantity %>
  </td>
  <td>
    <%= number_to_currency item.product.price %>
  </td>
  <td>
<%= number_to_currency item.total_price %>
</td>
  </tr>
  <% end %>
</tbody>
</table>

<h1>Order Subtotal: <%= number_to_currency @cart.subtotal %></h1>

<%= button_to "Empty Cart", @cart, method: :delete, data: {confirm: "Are You Sure"}, class: "btn btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <meta charset="utf=8">
  <meta charset="utf=8">
  <meta http=equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js" %>
  <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_api_key'] %>&callback=initMap" async defer></script>
  <%= csrf_meta_tags %>
</head>
  <body>

  <div class="container">
  <div class="pull-right">
    <% if user_signed_in? %>
      <%= link_to "Home", root_path, class: "btn btn-warning" %>
      <%= link_to "My Profile", profile_path(current_user.id), class: "btn btn-success" %>
      <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    <% end %>
  </div>
      <%= yield %>
  </div>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
<div class="field form-group">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div><br />
<div class="field form-group">
  <%= f.label :price %>
  <%= f.number_field :price %>
</div><br />
<div class="field form-group">
  <%= f.label :description %><br />
  <%= f.text_area :description %>
</div><br />
<div class="field form-group">
  <%= f.label :quantity %>
  <%= f.number_field :quantity %>
</div><br />
<div class="field form-group">
  <%= f.label :address %>
  <%= f.text_field :address %>
</div><br />
<div class="form-group">
  <%= f.label "Condition" %>
  <%= f.collection_select(:condition_id, Condition.all, :id, :status) %>
</div><br />
<div class="form-group">
  <%= f.label "Category" %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
</div><br />
<div class="field form-group">
    <%= f.label "Product Photo" %><br>
    <%= f.file_field :pic %>
</div><br />
<div class="form-group cant-see-me">
  <%= f.number_field :user_id, value: current_user.id %>
</div>
<div class="actions">
  <%= f.submit %>
</div>

<% end %>

<%= link_to "Back", products_path, class: "btn btn-primary" %>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<h1>Products</h1>

<%= link_to "New Listing", new_product_path, class: "btn btn-primary" %>

<br />
<div class="row">
  <% @product.each do |product| %>
    <div class="col-md-4">
      <div class="panel panel-body">
        <h1><%= link_to product.name, product %></h1>
        <p>Pice: <%= product.price %></p>
        <p>Description: <%= product.description[0..100] %>..[<%= link_to "See More", product %>]</p>
        <p>Location: <%= product.address %> </p>
        <p>Distance: <%= product.distance_to(current_user).round(2) %> Miles</p>
      </div>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New Products</h1>

<%= render 'form' %>

app/views/products/show.html.erb
<h1>Product</h1>

<div class="jumbotron">
  <div class="panel panel-heading">
    <h1><strong><%= @product.name %></strong></h1><br />
    <h3>Price: <%= @product.price %></h3>
  </div>
  <div class="panel panel-body">
    <p>Description:</p><h5> <%= @product.description %></h5><br />
    <p>Quantity: <%= @product.quantity %></p>
    <p>Location: <%= @product.address %></p>
    <% if @product.pic_file_name != nil %>
    <%= image_tag @product.pic.url(:medium), class: "img-responsive" %>
   <% end %>
  </div>
</div>

<%= button_to "Add to Cart", line_items_path(product_id: @product), class: "btn btn-success" %>

<div class= "wrap">

</div>

<div id="map-canvas"></div>
<%= javascript_tag do %>
  latitude = '<%= j @product.latitude.to_s %>';
  longitude = '<%= j @product.longitude.to_s %>';
  title = '<%= j @product.name %>'
<% end %>

<%= link_to "Back", products_path, class: "btn btn-primary" %>

app/views/profiles/show.html.erb
<h1><%= @user.username %>'s Profile</h1>

<% if @user.avatar_file_name != nil %>
   <%= image_tag @user.avatar.url(:medium), class: "img-responsive" %>
<% end %>
<br />
<p>Distance from User: <%= current_user.distance_to(@user).round(2) %></p>
<br />


<%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %>
<%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>